name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  PORT: 8080
jobs:
  test:
    environment: testing
    env:
      MONGODB_DB_NAME: test
      MONGODB_CLUSTER_ADDRESS: cluster0.z2iobfe.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGO_USERNAME: ${{env.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "..."
